# Configuration docker pour déployer theses.fr
# avant de lancer docker-compose up, il est nécessaire
# de copier le fichier .env-dist dans le fichier .env
# puis de personnaliser le contenu du fichier .env
version: "3.5"

services:

  # theses-rp est le reverse proxy application de theses.fr
  # toutes les requêtes HTTP passent par lui, il est chargé
  # d'authentifier les utilisateurs avec la fédération d'identités
  # RENATER lorsque ce derniers accèdent à /74979_GERARDIN_2018_archivage.pdf
  # (à adapter)
  theses-rp:
    container_name: theses-rp
    image: abesesr/docker-shibboleth-renater-sp:1.0.3
    ports:
      - 443:443
      - 10300:443
    environment:
      RENATER_SP_TEST_OR_PROD: 
      RENATER_SP_ENTITY_ID: 
      RENATER_SP_ADMIN_MAIL: 
      RENATER_SP_HTTPD_SERVER_NAME: 
      RENATER_SP_HTTPD_LOG_LEVEL: "info ssl:warn"
      RENATER_SP_HTTPD_PROTECTED_PATH: "/74979_GERARDIN_2018_archivage.pdf"
      RENATER_SP_HTTPD_PUBLIC_PROXY_TO: "http://theses-api-diffusion/"
      RENATER_SP_HTTPD_PROTECTED_PROXY_TO: "http://theses-api-diffusion/74979_GERARDIN_2018_archivage.pdf"
    restart: unless-stopped
    depends_on:
      - theses-api-diffusion
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=theses"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=apache"


  # API de diffusion des thèses en java spring de theses.fr
  # (travail en cours, pour la preuve de concept il est
  #  chargé de mettre à disposition un PDF en 
  #  accès restreint que theses-rp protège)
  theses-api-diffusion:
    container_name: theses-api-diffusion
    #image: mendhak/http-https-echo:23
    build: ./images/theses-api-diffusion/
    image: httpd:2.4.54-theses-api-diffusion
    ports:
      - 10301:80
    restart: unless-stopped
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=theses"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=apache"

