#
# Ci-dessous la config qui permet de lancer le système de déploiement en continue de theses-docker
# cf README.md pour explications: https://github.com/abes-esr/theses-docker#d%C3%A9ploiement-continu
#

version: "3"

services:

  # Conteneur chargé de mettre à jour automatiquement toutes les 10 secondes 
  # les images docker des conteneurs theses-front (cf paramètre dernière ligne)
  # cela permet de faire du déploiement continue en attendant les déploiement Ansible 
  # ce conteneur devra donc être supprimé une fois que le déploiement Ansible sera en place
  # plus d'info : https://containrrr.dev/watchtower
  theses-watchtower:
    image: containrrr/watchtower:1.4.0
    container_name: theses-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 10
      WATCHTOWER_DEBUG: "false"
    command: theses-front
   
