receivers:
  docker_stats:
    api_version: "1.54"
    container_labels_to_metric_labels:
      my.container.label: my-metric-label
      my.other.container.label: my-other-metric-label
    env_vars_to_metric_labels:
      OTEL_NAMESPACE: ${OTEL_NAMESPACE}
      MY_ENVIRONMENT_VARIABLE: my-metric-label
      MY_OTHER_ENVIRONMENT_VARIABLE: my-other-metric-label
    excluded_images:
      - ^(?!.*theses).*$

processors:
  resource/set_service_name:
    attributes:
      - key: service.name
        from_attribute: container.name
        action: insert

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      processors: [resource/set_service_name]
      exporters: [otlp]
