receivers:
  docker_stats:
    api_version: "1.54"
    env_vars_to_metric_labels:
      OTEL_NAMESPACE: service.namespace
      OTEL_ENVIRONMENT: deployment.environment

processors:
  resource:
    attributes:
      - key: service.name
        from_attribute: container.name
        action: upsert

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      processors: [resource]
      exporters: [otlp]
