# Configuration des récepteurs de métriques pour la machine hôte
receivers:
  host_metrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      network:

# Configuration des processeurs pour transformer les données collectées
processors:
  # Utilisation du processeur standard resource pour définir les attributs de la machine hôte
  resource:
    attributes:
      - key: service.name
        value: ${HOSTNAME}
        action: upsert
      - key: deployment.environment
        value: ${OTEL_ENVIRONMENT}
        action: upsert
      - key: service.namespace
        value: ${HOSTNAME}
        action: upsert
      - key: host.name
        value: ${HOSTNAME}
        action: upsert

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
    tls:
      insecure: true

# Définition des pipelines de collecte de télémétrie
service:
  pipelines:
    metrics:
      receivers: [host_metrics]
      processors: [resource]
      exporters: [otlp]
