receivers:
  containers_metrics:
    api_version: "1.54"
    env_vars_to_metric_labels:
      OTEL_NAMESPACE: service.namespace
      OTEL_ENVIRONMENT: deployment.environment

processors:
  resource_mapping:
    attributes:
      - key: service.name
        from_attribute: container.name
        action: upsert
  resource_detection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [containers_metrics]
      processors: [resource_mapping, resource_detection/docker]
      exporters: [otlp]
