# Configuration des récepteurs de métriques
receivers:
  # Utilisation du récepteur standard docker_stats pour collecter les métriques Docker
  docker_stats:
    api_version: "1.54"
    env_vars_to_metric_labels:
      OTEL_ENVIRONMENT: deployment.environment
      HOSTNAME: host.name

# Configuration des processeurs pour transformer les données collectées
processors:
  # Utilisation du processeur standard resource pour mapper les attributs de ressources
  resource:
    attributes:
      - key: service.name
        from_attribute: container.name
        action: upsert

  resource_detection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT_GRPC}
    tls:
      insecure: true

# Définition des pipelines de collecte de télémétrie
service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      processors: [resource, resource_detection/docker]
      exporters: [otlp]
